apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-service
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/jvm-build-service/jvm-build-service@sha256:c428955918a15711af084c6eb2f8d4d9ff9879deba45625b2d0c91f3766c23d9
        name: container-image
        resources: {}
status: {}
