apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: jvm-build-service-cache
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/jvm-build-service/jvm-build-service-cache@sha256:7d465dd47aa0b65479d824981f0a5733a02d228bd1d0392597542a48d5ee5533
        name: my-java-quarkus
        resources: {}
status: {}
