apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-service-cache
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-service-cache
    app.kubernetes.io/part-of: jvm-build-service
  name: jvm-build-service-cache
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: jvm-build-service-cache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: jvm-build-service-cache
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/jvm-build-service/jvm-build-service-cache@sha256:36f23d9b823f10c9b6013e2c48696283746e453ba45ca46a7e144e98f8af8be3
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
