apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jvm-build-service-cache
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvm-build-service-cache
    app.kubernetes.io/part-of: jvm-build-service
  name: jvm-build-service-cache
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: jvm-build-service-cache
status:
  loadBalancer: {}
